[package]
name = "nature-of-code"
version = "0.1.0"
authors = ["Jeriel <jeriel.verissimo@protonmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
sdl2 = "0.34.0"
rand = "0.7.3"
